services:
  postgres:
    image: postgres:16
    container_name: aegis_postgres
    environment:
      POSTGRES_DB: aegis
      POSTGRES_USER: aegis
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - aegis:/var/lib/postgresql/data

volumes:
  aegis: